### PR TITLE
Removing WMAgent dependence on DBS2 Client

### PR DESCRIPTION
**Pull request by alexanderrichards**
Temp PR to get the diff

### CODE REVIEW

**Comment by alexanderrichards** [comment]
I removed the dbs-client.spec file as well as the explicit dependence from wmagent.spec. This will cause problems as more than just wmagent depends on this API. The list is:

./asyncstageout.spec
./crabserver.spec
./crabtaskworker.spec
./dbs3-client.spec
./dls-client.spec
./workqueue.spec

Should I leave the dbs-client.spec file around for these dependencies or do they also need to change?

Interestingly I note that dbs3-client seems to depend on the dbs-client. Is that expected?

```
%build
python setup.py build_system -s dbs-client
%install
<snip>
python setup.py install_system -s dbs-client --prefix=%i
```

Although this is probably defining what it is built and installed as rather than a dependency right?

**Comment by alexanderrichards** [comment]
clearly the workqueue we can change but as we have no control over the crab code for example it's probably best I leave the dbs-client.spec file where it is and just remove the dependence on it from wmagent.spec right?

Do we also want to do this for workqueue?

**Comment by amaltaro** [comment]
Good question! I don't know the answer, but we either:
 1) remove the dependency from wmagent spec only
 2) remove the dependency from _all_ specs and remove that spec itself.

Though, we may want to do this when we have more time, so for April's cmsweb cycle.

**Comment by ticoann** [comment]
Yes, I agree with Alan,  1 has been done,
https://github.com/cms-sw/cmsdist/pull/2110

For 2, we shouldn't do by ourselves. We should let other people responsible to handle that. 
And finally Yuyi should be responsible to remove dbs-client when all other package remove the dependency

**Pull request closed without merging**
